name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure CMake
        run: |
          cmake -S . -B build/${{ matrix.build_type }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: |
          cmake --build build/${{ matrix.build_type }} --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: build/${{ matrix.build_type }}
        run: |
          ctest --output-on-failure -C ${{ matrix.build_type }}

